// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VHSmart_Api.Shared.Infrastructure.Persistence;

#nullable disable

namespace VHSmart_Api.Shared.Infrastructure.Migrations
{
    [DbContext(typeof(VHSmartDbContext))]
    [Migration("20260930015159_UsersAndLogin")]
    partial class UsersAndLogin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VHSmart_Api.Shared.Domain.Admin.DocumentSequenceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LastNumber")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("SysDateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SysDateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("SysUserCreated")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SysUserModified")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Scope")
                        .IsUnique();

                    b.ToTable("AdmDocumentSequences", (string)null);
                });

            modelBuilder.Entity("VHSmart_Api.Shared.Domain.Admin.NotificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("SysDateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SysDateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("SysUserCreated")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SysUserModified")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("AdmNotifications", (string)null);
                });

            modelBuilder.Entity("VHSmart_Api.Shared.Domain.Admin.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("SysDateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SysDateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("SysUserCreated")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SysUserModified")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AdmRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            IsDeleted = false,
                            IsSystemRole = true,
                            Name = "VH Smart Admin",
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("c0603c53-253e-4d16-55fc-b2fac9cc3be3"),
                            IsDeleted = false,
                            IsSystemRole = true,
                            Name = "Auditor / Chief Auditor",
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("38ce3603-fddc-3cea-a130-16305f495c9e"),
                            IsDeleted = false,
                            IsSystemRole = true,
                            Name = "Restaurant / Premise Manager",
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        });
                });

            modelBuilder.Entity("VHSmart_Api.Shared.Domain.Admin.RolePermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanCreate")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("bit");

                    b.Property<bool>("CanView")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SysDateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SysDateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("SysUserCreated")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SysUserModified")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId", "PermissionKey")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("AdmRolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("57416391-5157-635b-3c53-f59b443986b4"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Dashboard",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("d2a484e4-23d9-a768-5c24-fe68769f455a"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Admin.GeneralData",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("f04be36d-63a7-1718-cd03-1e0384659c38"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Admin.CertificationBodies",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("4da02def-132b-ecdb-0220-526164cfd12e"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Admin.ServiceProviders",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("5f031a38-4069-bd83-1ecb-dc6af26eae10"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Admin.WebLinks",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("e1bc766d-ebe5-bf79-e061-da9282aa5dc6"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Admin.SupportingDocuments",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("788aa22b-cbd7-8dfd-c90c-5729e93cb6b3"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Admin.Companies",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("c9f0bc1c-0317-3f8d-4f1f-d47b4f10cf2f"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Admin.Users",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("8056a50e-ece4-1ec8-21e7-f4fe56162f60"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "AdvancedSearch",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("f8e525ad-07af-a24e-683c-b464ecaee789"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Company.General",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("1f01c317-a6c5-6b5e-918e-b2ab90e2babd"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Company.HalalPolicy",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("8af3d138-ff46-f043-56d3-a3e627a1fbbd"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Company.Profiles",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("98908295-f823-57e0-f31b-f513f5c45083"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Company.InternalHalalCommittee",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("a5e2165b-c904-3939-9343-f6d724bf66c3"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Personnel.AllStaff",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("cdf9f3b9-0188-af7c-569f-1132e3e8e801"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Personnel.InternalTraining",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("27808135-9417-2625-9032-7c11d4e596ff"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Premise.ManagePremise",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("07ec2fe0-7ab7-43e5-bbb6-173326e549aa"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Product.ManageProduct",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("48b31025-18c5-7b71-8f64-a5bb0f57488d"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Product.ManageMenu",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("669cbff2-c47f-7efc-fc46-4f378012a39c"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Product.ManageMenuConcept",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("8dca8f30-205c-4ed5-9ab7-56680843e2f5"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Product.VerifyHalalProductUpdate",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("f7e8aeb6-cf8a-c030-dbaf-19fb300aa9e1"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "RawMaterial.ManufacturerSupplier",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("452b7f47-054d-0b33-7b81-e8f1441c488c"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "RawMaterial.MasterList",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("96ce4195-b5dc-147a-e0fb-83c97eb43dce"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "HalalApplication.ManageBatch",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("59e3d80b-a777-3cb4-0dd4-6f64f33d91b2"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "HalalApplication.MyApplication",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("01a6a1a4-30d2-be5f-9e69-bcbb0c8279fa"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "HalalApplication.CertificateItem",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("12c30412-1dd2-81d4-8776-43492d79dbc8"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "HalalApplication.HalalCertificate",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("39a56b38-7730-53ee-75f2-6572cdd067ac"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Audit.AuditPrefix",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("6d0f41b6-5189-08a9-95cd-8bc496c98d9c"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Audit.Recommendation",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("79c737bf-fc18-02ce-0599-16936eee1c79"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Audit.Finding",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("a75c63e5-c10f-4ec5-2e32-09e6950c3626"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Audit.AuditCriteria",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("43067f91-fc07-30b9-2ecd-d08a6c1e1270"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Audit.AuditChecklist",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("ddc32abe-5489-4d64-85eb-4605ac18613d"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Audit.GroupAuditor",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("995994e3-4066-1a84-a2a4-c05ad828bd75"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Audit.AuditPlanning",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("e4ef5bde-f14c-9a3b-f1d7-e8ae1d4c1295"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Audit.AuditTask",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("70f4b033-5cd1-68f8-981a-f99f3cb7a609"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Audit.ExternalReport",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("9f541486-2462-bd3b-3683-4f0696d8e6f3"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Audit.NonConformance",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("340c803b-149c-bf70-a83c-5abd1c0fe244"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Payment.Certificate",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("b9b7c460-2a01-2609-3792-106e7a8c4c04"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Payment.Other",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("89f74c93-9039-14c6-98fd-b620817c9293"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Reference.View",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("c5608897-fdb1-f0ab-d032-e6f7b43c36b6"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Support.Submit",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("0d0b78cd-4cac-d3bd-f0e2-2dc98e11470f"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Account.Setting",
                            RoleId = new Guid("9541c127-bd5a-0859-35e6-e00fc02e6ab2"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("0bda2516-e0f4-e60f-c170-9923ebca95d7"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Audit.AuditPrefix",
                            RoleId = new Guid("c0603c53-253e-4d16-55fc-b2fac9cc3be3"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("f7c120fc-84c8-aa0e-1b01-95db266e17f3"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Audit.Recommendation",
                            RoleId = new Guid("c0603c53-253e-4d16-55fc-b2fac9cc3be3"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("c78dda7e-9970-6cf3-10a4-1295942863ad"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Audit.Finding",
                            RoleId = new Guid("c0603c53-253e-4d16-55fc-b2fac9cc3be3"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("9093e27e-ec2c-18c0-6d15-91983ca70f34"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Audit.AuditCriteria",
                            RoleId = new Guid("c0603c53-253e-4d16-55fc-b2fac9cc3be3"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("f83ca4e3-1269-471a-430e-7dc82125c4db"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Audit.AuditChecklist",
                            RoleId = new Guid("c0603c53-253e-4d16-55fc-b2fac9cc3be3"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("71373fc5-d10f-f999-f08c-83d5b6f03753"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Audit.GroupAuditor",
                            RoleId = new Guid("c0603c53-253e-4d16-55fc-b2fac9cc3be3"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("418e7418-435f-026a-cc28-0375b418ef9a"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Audit.AuditPlanning",
                            RoleId = new Guid("c0603c53-253e-4d16-55fc-b2fac9cc3be3"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("9cd85218-bf15-79c4-7649-9a4b0008d383"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Audit.AuditTask",
                            RoleId = new Guid("c0603c53-253e-4d16-55fc-b2fac9cc3be3"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("f71ed060-778a-e5fd-7f98-5f7499508dd4"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Audit.ExternalReport",
                            RoleId = new Guid("c0603c53-253e-4d16-55fc-b2fac9cc3be3"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("3b6f37c4-2deb-5cf2-4c96-2fa1dc4c1ec2"),
                            CanCreate = true,
                            CanDelete = true,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Audit.NonConformance",
                            RoleId = new Guid("c0603c53-253e-4d16-55fc-b2fac9cc3be3"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("79cc9636-9b91-0429-cd0a-b8abb0e8b6ac"),
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Dashboard",
                            RoleId = new Guid("c0603c53-253e-4d16-55fc-b2fac9cc3be3"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("7e118721-b35b-3785-a314-afe9c3432717"),
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Account.Setting",
                            RoleId = new Guid("c0603c53-253e-4d16-55fc-b2fac9cc3be3"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("08dbba6f-be39-f4d4-1805-ca180f66733f"),
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Admin.GeneralData",
                            RoleId = new Guid("c0603c53-253e-4d16-55fc-b2fac9cc3be3"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("c4005bf1-8bbc-45f2-bf8c-a0ec973644a9"),
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Premise.ManagePremise",
                            RoleId = new Guid("c0603c53-253e-4d16-55fc-b2fac9cc3be3"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("40884517-2c47-1be1-dd8d-6c582e27cbc2"),
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Dashboard",
                            RoleId = new Guid("38ce3603-fddc-3cea-a130-16305f495c9e"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("72aa9565-41cd-fd52-9de5-e6d5840e26a6"),
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Account.Setting",
                            RoleId = new Guid("38ce3603-fddc-3cea-a130-16305f495c9e"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("3507b5f8-671a-0c58-2d56-42da25d0f617"),
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Premise.ManagePremise",
                            RoleId = new Guid("38ce3603-fddc-3cea-a130-16305f495c9e"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        },
                        new
                        {
                            Id = new Guid("6e85b8fd-f7cf-1bf5-5224-554b3331eed4"),
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = true,
                            CanView = true,
                            IsDeleted = false,
                            PermissionKey = "Audit.NonConformance",
                            RoleId = new Guid("38ce3603-fddc-3cea-a130-16305f495c9e"),
                            SysDateCreated = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            SysUserCreated = "system"
                        });
                });

            modelBuilder.Entity("VHSmart_Api.Shared.Domain.Admin.UserCompanyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SysDateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SysDateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("SysUserCreated")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SysUserModified")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId", "CompanyId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("AdmUserCompanies", (string)null);
                });

            modelBuilder.Entity("VHSmart_Api.Shared.Domain.Admin.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContactNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPlatformAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SysDateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SysDateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("SysUserCreated")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SysUserModified")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("RoleId");

                    b.ToTable("AdmUsers", (string)null);
                });

            modelBuilder.Entity("VHSmart_Api.Shared.Domain.Admin.UserTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("SysDateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SysDateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("SysUserCreated")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SysUserModified")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("AdmUserTokens", (string)null);
                });

            modelBuilder.Entity("VHSmart_Api.Shared.Domain.Admin.NotificationEntity", b =>
                {
                    b.HasOne("VHSmart_Api.Shared.Domain.Admin.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VHSmart_Api.Shared.Domain.Admin.RolePermissionEntity", b =>
                {
                    b.HasOne("VHSmart_Api.Shared.Domain.Admin.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VHSmart_Api.Shared.Domain.Admin.UserCompanyEntity", b =>
                {
                    b.HasOne("VHSmart_Api.Shared.Domain.Admin.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VHSmart_Api.Shared.Domain.Admin.UserEntity", b =>
                {
                    b.HasOne("VHSmart_Api.Shared.Domain.Admin.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("VHSmart_Api.Shared.Domain.StoredFile", "ProfilePicture", b1 =>
                        {
                            b1.Property<Guid>("UserEntityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(260)
                                .HasColumnType("nvarchar(260)");

                            b1.Property<long>("SizeBytes")
                                .HasColumnType("bigint");

                            b1.Property<string>("StorageKey")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("UserEntityId");

                            b1.ToTable("AdmUsers");

                            b1.WithOwner()
                                .HasForeignKey("UserEntityId");
                        });

                    b.Navigation("ProfilePicture");
                });

            modelBuilder.Entity("VHSmart_Api.Shared.Domain.Admin.UserTokenEntity", b =>
                {
                    b.HasOne("VHSmart_Api.Shared.Domain.Admin.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
