using System.Security.Cryptography;
using FluentValidation;
using MediatR;
using Microsoft.EntityFrameworkCore;
using VHSmart_Api.Shared.Domain.Admin;
using VHSmart_Api.Shared.Exceptions;
using VHSmart_Api.Shared.Infrastructure.Persistence;
using VHSmart_Api.Shared.Infrastructure.Security;

namespace VHSmart_Api.Features.Auth.Activation;

// Account activation (spec 3.2: "Default password is generated by the system when the
// account is activated"; spec 3.4 legacy flow, re-built without the e-mail). The caller
// presents the one-time token from Add User / Re-issue; the server then generates the
// default password, stores only its hash, activates the account and returns the password
// exactly once - MustChangePassword forces a change at the first login (CodingRules 8.3).
// Anonymous by design: this is the activation step, one of the three [AllowAnonymous] paths.
public record ActivateCommand(string Token) : IRequest<ActivateResponse>;

public class ActivateValidator : AbstractValidator<ActivateCommand>
{
    public ActivateValidator()
    {
        RuleFor(x => x.Token)
            .NotEmpty().WithMessage("Activation token is required.");
    }
}

public record ActivateResponse(Guid UserId, string Email, string Password);

public class ActivateHandler(VHSmartDbContext db)
    : IRequestHandler<ActivateCommand, ActivateResponse>
{
    // No strength rule exists yet (Q13): 16 random alphanumeric characters, generated by
    // the CSPRNG, is far beyond anything the legacy default offered.
    private const int PasswordLength = 16;

    private const string InvalidTokenMessage = "Invalid or expired activation token.";

    private const string Alphabet =
        "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

    public async Task<ActivateResponse> Handle(ActivateCommand request, CancellationToken ct)
    {
        // Lookup by the stored hash: the raw token is never persisted (Database.md 5) and the
        // global filter hides tokens of soft-deleted users, so they can never activate.
        var tokenHash = OneTimeToken.Hash(request.Token.Trim());
        var token = await db.UserTokens
            .SingleOrDefaultAsync(row =>
                row.TokenHash == tokenHash
                && row.Purpose == UserTokenPurpose.Activation
                && row.UsedAt == null
                && row.ExpiresAt > DateTime.UtcNow, ct);
        if (token is null)
            throw new NotFoundException(InvalidTokenMessage);

        var user = await db.Users
            .SingleOrDefaultAsync(row => row.Id == token.UserId, ct);
        if (user is null)
            throw new NotFoundException(InvalidTokenMessage);

        var password = GeneratePassword();
        user.PasswordHash = UserPasswordHasher.Hash(user, password);
        user.MustChangePassword = true;
        user.ActivatedAt = DateTime.UtcNow;
        user.IsActive = true;
        user.FailedLoginCount = 0;
        user.LockedUntil = null;

        token.UsedAt = DateTime.UtcNow;

        await db.SaveChangesAsync(ct);

        return new ActivateResponse(user.Id, user.Email, password);
    }

    private static string GeneratePassword()
    {
        var characters = new char[PasswordLength];
        for (var index = 0; index < characters.Length; index++)
            characters[index] = Alphabet[RandomNumberGenerator.GetInt32(Alphabet.Length)];
        return new string(characters);
    }
}
