using System.Security.Cryptography;
using System.Text;
using VHSmart_Api.Shared.Domain.Admin;

namespace VHSmart_Api.Shared.Infrastructure.Persistence;

// Seed rows for the R-01 reference lookups: the full ISO 3166-1 country list and the Malaysian
// states (Database.md 14), plus the 9 schemes of the halal-application picker (spec 12.1).
// HasData runs once inside the migration - like RoleSeedData - so rows the owner later edits
// through the API are never overwritten at startup. Every id is a hash of a fixed key so each
// machine generates the same migration.
public static class ReferenceSeedData
{
    private const string SeedUser = "system";

    private static readonly DateTime SeedDate = new(2026, 9, 30, 0, 0, 0, DateTimeKind.Utc);

    public static readonly Guid MalaysiaCountryId = StableId("country:MYS");

    // (ISO 3166-1 English short name, alpha-3 code), the full country list of Database.md 14.
    private static readonly IReadOnlyList<(string Name, string IsoCode)> Countries =
    [
        ("Afghanistan", "AFG"),
        ("Åland Islands", "ALA"),
        ("Albania", "ALB"),
        ("Algeria", "DZA"),
        ("American Samoa", "ASM"),
        ("Andorra", "AND"),
        ("Angola", "AGO"),
        ("Anguilla", "AIA"),
        ("Antarctica", "ATA"),
        ("Antigua and Barbuda", "ATG"),
        ("Argentina", "ARG"),
        ("Armenia", "ARM"),
        ("Aruba", "ABW"),
        ("Australia", "AUS"),
        ("Austria", "AUT"),
        ("Azerbaijan", "AZE"),
        ("Bahamas", "BHS"),
        ("Bahrain", "BHR"),
        ("Bangladesh", "BGD"),
        ("Barbados", "BRB"),
        ("Belarus", "BLR"),
        ("Belgium", "BEL"),
        ("Belize", "BLZ"),
        ("Benin", "BEN"),
        ("Bermuda", "BMU"),
        ("Bhutan", "BTN"),
        ("Bolivia, Plurinational State of", "BOL"),
        ("Bonaire, Sint Eustatius and Saba", "BES"),
        ("Bosnia and Herzegovina", "BIH"),
        ("Botswana", "BWA"),
        ("Bouvet Island", "BVT"),
        ("Brazil", "BRA"),
        ("British Indian Ocean Territory", "IOT"),
        ("Brunei Darussalam", "BRN"),
        ("Bulgaria", "BGR"),
        ("Burkina Faso", "BFA"),
        ("Burundi", "BDI"),
        ("Cabo Verde", "CPV"),
        ("Cambodia", "KHM"),
        ("Cameroon", "CMR"),
        ("Canada", "CAN"),
        ("Cayman Islands", "CYM"),
        ("Central African Republic", "CAF"),
        ("Chad", "TCD"),
        ("Chile", "CHL"),
        ("China", "CHN"),
        ("Christmas Island", "CXR"),
        ("Cocos (Keeling) Islands", "CCK"),
        ("Colombia", "COL"),
        ("Comoros", "COM"),
        ("Congo", "COG"),
        ("Congo, Democratic Republic of the", "COD"),
        ("Cook Islands", "COK"),
        ("Costa Rica", "CRI"),
        ("Côte d'Ivoire", "CIV"),
        ("Croatia", "HRV"),
        ("Cuba", "CUB"),
        ("Curaçao", "CUW"),
        ("Cyprus", "CYP"),
        ("Czechia", "CZE"),
        ("Denmark", "DNK"),
        ("Djibouti", "DJI"),
        ("Dominica", "DMA"),
        ("Dominican Republic", "DOM"),
        ("Ecuador", "ECU"),
        ("Egypt", "EGY"),
        ("El Salvador", "SLV"),
        ("Equatorial Guinea", "GNQ"),
        ("Eritrea", "ERI"),
        ("Estonia", "EST"),
        ("Eswatini", "SWZ"),
        ("Ethiopia", "ETH"),
        ("Falkland Islands (Malvinas)", "FLK"),
        ("Faroe Islands", "FRO"),
        ("Fiji", "FJI"),
        ("Finland", "FIN"),
        ("France", "FRA"),
        ("French Guiana", "GUF"),
        ("French Polynesia", "PYF"),
        ("French Southern Territories", "ATF"),
        ("Gabon", "GAB"),
        ("Gambia", "GMB"),
        ("Georgia", "GEO"),
        ("Germany", "DEU"),
        ("Ghana", "GHA"),
        ("Gibraltar", "GIB"),
        ("Greece", "GRC"),
        ("Greenland", "GRL"),
        ("Grenada", "GRD"),
        ("Guadeloupe", "GLP"),
        ("Guam", "GUM"),
        ("Guatemala", "GTM"),
        ("Guernsey", "GGY"),
        ("Guinea", "GIN"),
        ("Guinea-Bissau", "GNB"),
        ("Guyana", "GUY"),
        ("Haiti", "HTI"),
        ("Heard Island and McDonald Islands", "HMD"),
        ("Holy See", "VAT"),
        ("Honduras", "HND"),
        ("Hong Kong", "HKG"),
        ("Hungary", "HUN"),
        ("Iceland", "ISL"),
        ("India", "IND"),
        ("Indonesia", "IDN"),
        ("Iran, Islamic Republic of", "IRN"),
        ("Iraq", "IRQ"),
        ("Ireland", "IRL"),
        ("Isle of Man", "IMN"),
        ("Israel", "ISR"),
        ("Italy", "ITA"),
        ("Jamaica", "JAM"),
        ("Japan", "JPN"),
        ("Jersey", "JEY"),
        ("Jordan", "JOR"),
        ("Kazakhstan", "KAZ"),
        ("Kenya", "KEN"),
        ("Kiribati", "KIR"),
        ("Korea, Democratic People's Republic of", "PRK"),
        ("Korea, Republic of", "KOR"),
        ("Kuwait", "KWT"),
        ("Kyrgyzstan", "KGZ"),
        ("Lao People's Democratic Republic", "LAO"),
        ("Latvia", "LVA"),
        ("Lebanon", "LBN"),
        ("Lesotho", "LSO"),
        ("Liberia", "LBR"),
        ("Libya", "LBY"),
        ("Liechtenstein", "LIE"),
        ("Lithuania", "LTU"),
        ("Luxembourg", "LUX"),
        ("Macao", "MAC"),
        ("Madagascar", "MDG"),
        ("Malawi", "MWI"),
        ("Malaysia", "MYS"),
        ("Maldives", "MDV"),
        ("Mali", "MLI"),
        ("Malta", "MLT"),
        ("Marshall Islands", "MHL"),
        ("Martinique", "MTQ"),
        ("Mauritania", "MRT"),
        ("Mauritius", "MUS"),
        ("Mayotte", "MYT"),
        ("Mexico", "MEX"),
        ("Micronesia, Federated States of", "FSM"),
        ("Moldova, Republic of", "MDA"),
        ("Monaco", "MCO"),
        ("Mongolia", "MNG"),
        ("Montenegro", "MNE"),
        ("Montserrat", "MSR"),
        ("Morocco", "MAR"),
        ("Mozambique", "MOZ"),
        ("Myanmar", "MMR"),
        ("Namibia", "NAM"),
        ("Nauru", "NRU"),
        ("Nepal", "NPL"),
        ("Netherlands, Kingdom of the", "NLD"),
        ("New Caledonia", "NCL"),
        ("New Zealand", "NZL"),
        ("Nicaragua", "NIC"),
        ("Niger", "NER"),
        ("Nigeria", "NGA"),
        ("Niue", "NIU"),
        ("Norfolk Island", "NFK"),
        ("North Macedonia", "MKD"),
        ("Northern Mariana Islands", "MNP"),
        ("Norway", "NOR"),
        ("Oman", "OMN"),
        ("Pakistan", "PAK"),
        ("Palau", "PLW"),
        ("Palestine, State of", "PSE"),
        ("Panama", "PAN"),
        ("Papua New Guinea", "PNG"),
        ("Paraguay", "PRY"),
        ("Peru", "PER"),
        ("Philippines", "PHL"),
        ("Pitcairn", "PCN"),
        ("Poland", "POL"),
        ("Portugal", "PRT"),
        ("Puerto Rico", "PRI"),
        ("Qatar", "QAT"),
        ("Réunion", "REU"),
        ("Romania", "ROU"),
        ("Russian Federation", "RUS"),
        ("Rwanda", "RWA"),
        ("Saint Barthélemy", "BLM"),
        ("Saint Helena, Ascension and Tristan da Cunha", "SHN"),
        ("Saint Kitts and Nevis", "KNA"),
        ("Saint Lucia", "LCA"),
        ("Saint Martin (French part)", "MAF"),
        ("Saint Pierre and Miquelon", "SPM"),
        ("Saint Vincent and the Grenadines", "VCT"),
        ("Samoa", "WSM"),
        ("San Marino", "SMR"),
        ("Sao Tome and Principe", "STP"),
        ("Saudi Arabia", "SAU"),
        ("Senegal", "SEN"),
        ("Serbia", "SRB"),
        ("Seychelles", "SYC"),
        ("Sierra Leone", "SLE"),
        ("Singapore", "SGP"),
        ("Sint Maarten (Dutch part)", "SXM"),
        ("Slovakia", "SVK"),
        ("Slovenia", "SVN"),
        ("Solomon Islands", "SLB"),
        ("Somalia", "SOM"),
        ("South Africa", "ZAF"),
        ("South Georgia and the South Sandwich Islands", "SGS"),
        ("South Sudan", "SSD"),
        ("Spain", "ESP"),
        ("Sri Lanka", "LKA"),
        ("Sudan", "SDN"),
        ("Suriname", "SUR"),
        ("Svalbard and Jan Mayen", "SJM"),
        ("Sweden", "SWE"),
        ("Switzerland", "CHE"),
        ("Syrian Arab Republic", "SYR"),
        ("Taiwan, Province of China", "TWN"),
        ("Tajikistan", "TJK"),
        ("Tanzania, United Republic of", "TZA"),
        ("Thailand", "THA"),
        ("Timor-Leste", "TLS"),
        ("Togo", "TGO"),
        ("Tokelau", "TKL"),
        ("Tonga", "TON"),
        ("Trinidad and Tobago", "TTO"),
        ("Tunisia", "TUN"),
        ("Türkiye", "TUR"),
        ("Turkmenistan", "TKM"),
        ("Turks and Caicos Islands", "TCA"),
        ("Tuvalu", "TUV"),
        ("Uganda", "UGA"),
        ("Ukraine", "UKR"),
        ("United Arab Emirates", "ARE"),
        ("United Kingdom of Great Britain and Northern Ireland", "GBR"),
        ("United States of America", "USA"),
        ("United States Minor Outlying Islands", "UMI"),
        ("Uruguay", "URY"),
        ("Uzbekistan", "UZB"),
        ("Vanuatu", "VUT"),
        ("Venezuela, Bolivarian Republic of", "VEN"),
        ("Viet Nam", "VNM"),
        ("Virgin Islands (British)", "VGB"),
        ("Virgin Islands (U.S.)", "VIR"),
        ("Wallis and Futuna", "WLF"),
        ("Western Sahara", "ESH"),
        ("Yemen", "YEM"),
        ("Zambia", "ZMB"),
        ("Zimbabwe", "ZWE"),
    ];

    // Database.md 14 seeds the Malaysian states (13 states + 3 federal territories). Other
    // countries keep the free-text state on the owning record, so they have no rows here.
    private static readonly IReadOnlyList<string> MalaysianStates =
    [
        "Johor",
        "Kedah",
        "Kelantan",
        "Melaka",
        "Negeri Sembilan",
        "Pahang",
        "Perak",
        "Perlis",
        "Pulau Pinang",
        "Sabah",
        "Sarawak",
        "Selangor",
        "Terengganu",
        "Kuala Lumpur",
        "Labuan",
        "Putrajaya"
    ];

    // The 9 schemes of spec 12.1 in picker order. Abattoirs has no code in any screenshot -
    // Database.md 3 says to leave it null (VERIFY).
    private static readonly IReadOnlyList<SchemeSeed> Schemes =
    [
        new("PR", "Food and Beverages / Supplement Product", IsFoodPremise: false),
        new("PM", "Food Premises", IsFoodPremise: true),
        new(null, "Abattoirs", IsFoodPremise: false),
        new("BG", "Consumer's Good", IsFoodPremise: false),
        new("FM", "Pharmaceutical", IsFoodPremise: false),
        new("PL", "Logistics", IsFoodPremise: false),
        new("KO", "Cosmetics, Makeup & Personal Care(s)", IsFoodPremise: false),
        new("MD", "Medical Devices", IsFoodPremise: false),
        new("OEM", "Original Equipment Manufacturing (OEM)", IsFoodPremise: false)
    ];

    private sealed record SchemeSeed(string? Code, string Name, bool IsFoodPremise);

    public static IEnumerable<CountryEntity> CountryEntities() =>
        Countries.Select(country => new CountryEntity
        {
            Id = StableId($"country:{country.IsoCode}"),
            Name = country.Name,
            IsoCode = country.IsoCode,
            SysUserCreated = SeedUser,
            SysDateCreated = SeedDate
        });

    public static IEnumerable<StateEntity> StateEntities() =>
        MalaysianStates.Select(name => new StateEntity
        {
            Id = StableId($"state:MYS:{name}"),
            CountryId = MalaysiaCountryId,
            Name = name,
            SysUserCreated = SeedUser,
            SysDateCreated = SeedDate
        });

    public static IEnumerable<SchemeEntity> SchemeEntities() =>
        Schemes.Select((scheme, index) => new SchemeEntity
        {
            Id = StableId($"scheme:{scheme.Name}"),
            Code = scheme.Code,
            Name = scheme.Name,
            IsFoodPremise = scheme.IsFoodPremise,
            SortOrder = index + 1,
            SysUserCreated = SeedUser,
            SysDateCreated = SeedDate
        });

    private static Guid StableId(string value) =>
        new(SHA256.HashData(Encoding.UTF8.GetBytes(value))[..16]);
}
