// <auto-generated />
using System;
using IMAS_API_Example.Shared.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IMAS_API_Example.Migrations.ExampleDb
{
    [DbContext(typeof(ExampleDbContext))]
    [Migration("20250508030227_AddBaseClass")]
    partial class AddBaseClass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IMAS_API_Example.Entities.Example.ExampleEntities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ISDELETED")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SYSDATECREATED")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SYSDATEMODIFIED")
                        .HasColumnType("datetime2");

                    b.Property<string>("SYSUSERCREATED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SYSUSERMODIFIED")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ExampleEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
